FROM java:7u79-jre

MAINTAINER Manuel Ortiz Bey <ortiz.manuel@mozartanalytics.com>
MAINTAINER Andrés Amado <acactown@gmail.com>

# Copy sqsd builded version
ADD ./distributions/sqsd-@SQSD_VERSION@.zip /tmp/
RUN unzip /tmp/sqsd-@SQSD_VERSION@.zip -d /opt \
    && ln -s /opt/sqsd-@SQSD_VERSION@/bin/sqsd /usr/bin/sqsd \
    && rm -f /tmp/sqsd-@SQSD_VERSION@.zip

# Run sqsd
ENTRYPOINT ["sqsd"]
